resolver: lts-11.6

packages:
- '.'
extra-deps:
- inline-c-0.6.1.0

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []

allow-newer: true